<?php
declare(strict_types=1);

require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/session.php';
sqliteRequireLogin();

$driver = sqliteGetDriver();
$currentDb = $_GET['db'] ?? '';
$currentTable = $_GET['table'] ?? ($_POST['table'] ?? '');
$format = $_POST['format'] ?? 'sql';
$doExport = !empty($_POST['export']);

if (empty($currentDb)) {
    header('Location: databases.php');
    exit;
}

if ($doExport) {
    $filename = basename($currentDb, '.db');
    $filename = basename($filename, '.sqlite');
    $filename = basename($filename, '.sqlite3');
    $timestamp = date('Ymd_His');

    if ($format === 'download') {
        // Download the .db file directly
        $srv = null;
        require_once __DIR__ . '/../includes/config.php';
        global $sqliteServers;
        $serverIdx = $_SESSION['sqlite_server_idx'] ?? 0;
        $srv = $sqliteServers[$serverIdx] ?? null;

        if ($srv && $srv['mode'] === 'ssh') {
            // SSH: stream via ssh cat
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename="' . $filename . '.db"');
            $sshDriver = $driver;
            passthru($sshDriver->getSshPrefix() . ' ' . escapeshellarg('cat ' . escapeshellarg($currentDb)));
        } else {
            // Local: direct readfile
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename="' . $filename . '.db"');
            header('Content-Length: ' . filesize($currentDb));
            readfile($currentDb);
        }
        exit;
    }

    $tables = [];
    if ($currentTable !== '') {
        $tables = [$currentTable];
    } else {
        $tableList = $driver->tableList($currentDb);
        $tables = array_column($tableList, 'name');
    }

    if ($format === 'csv') {
        if (empty($currentTable)) {
            $currentTable = $tables[0] ?? '';
        }
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '_' . $currentTable . '_' . $timestamp . '.csv"');

        $output = fopen('php://output', 'w');
        $quotedTable = '"' . str_replace('"', '""', $currentTable) . '"';
        $rows = $driver->query($currentDb, 'SELECT * FROM ' . $quotedTable . ' LIMIT 10000');

        if (!empty($rows)) {
            fputcsv($output, array_keys($rows[0]));
            foreach ($rows as $row) {
                fputcsv($output, array_values($row));
            }
        }

        fclose($output);
        exit;
    }

    // SQL dump
    header('Content-Type: application/sql; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '_' . $timestamp . '.sql"');

    echo "-- SQLite dump generated by phpMyAdmin SQLite Admin\n";
    echo "-- Date: " . date('Y-m-d H:i:s') . "\n";
    echo "-- Database: " . basename($currentDb) . "\n\n";
    echo "BEGIN TRANSACTION;\n\n";

    foreach ($tables as $tbl) {
        $createSql = $driver->query($currentDb,
            "SELECT sql FROM sqlite_master WHERE name = '" . str_replace("'", "''", $tbl) . "'"
        );
        if (!empty($createSql[0]['sql'])) {
            echo $createSql[0]['sql'] . ";\n\n";
        }

        $quotedTable = '"' . str_replace('"', '""', $tbl) . '"';
        $rows = $driver->query($currentDb, 'SELECT * FROM ' . $quotedTable . ' LIMIT 10000');

        foreach ($rows as $row) {
            $cols = [];
            $vals = [];
            foreach ($row as $col => $val) {
                $cols[] = '"' . str_replace('"', '""', $col) . '"';
                if ($val === null) {
                    $vals[] = 'NULL';
                } elseif (is_int($val) || is_float($val)) {
                    $vals[] = $val;
                } else {
                    $vals[] = "'" . str_replace("'", "''", $val) . "'";
                }
            }
            echo 'INSERT INTO ' . $quotedTable . ' (' . implode(', ', $cols) . ') VALUES (' . implode(', ', $vals) . ");\n";
        }
        echo "\n";
    }

    echo "COMMIT;\n";
    exit;
}

$pageTitle = ($currentTable ?: basename($currentDb)) . ' - Export';
require_once __DIR__ . '/../includes/layout_header.php';
?>

<h4>Export <code><?= h($currentTable ?: basename($currentDb)) ?></code></h4>

<form method="post">
<?php if ($currentTable): ?>
    <input type="hidden" name="table" value="<?= h($currentTable) ?>">
<?php endif; ?>
    <div class="mb-3">
        <label class="form-label">Format</label>
        <div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="format" value="sql" id="fmt-sql" checked>
                <label class="form-check-label" for="fmt-sql">SQL Dump (CREATE + INSERT statements)</label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="format" value="csv" id="fmt-csv">
                <label class="form-check-label" for="fmt-csv">CSV<?= $currentTable ? '' : ' (first table only)' ?></label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="format" value="download" id="fmt-download">
                <label class="form-check-label" for="fmt-download">Download .db file</label>
            </div>
        </div>
    </div>
    <p class="text-muted">Max 10,000 rows per table for SQL/CSV exports.</p>
    <button type="submit" name="export" value="1" class="btn btn-success">Export</button>
    <a href="tables.php?db=<?= urlencode($currentDb) ?>" class="btn btn-secondary">Cancel</a>
</form>

<?php require_once __DIR__ . '/../includes/layout_footer.php'; ?>
